# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/VOR',
                'doc_host': 'https://niyazikemer.github.io',
                'git_url': 'https://github.com/niyazikemer/VOR',
                'lib_path': 'VOR'},
  'syms': {'VOR.core': {'VOR.core.foo': ('core.html#foo', 'VOR/core.py')}}}
